name: Build and Deploy
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
    - run:
          npm install -D vuepress
    - run:
          npm run docs:build
    - run: cd docs/.vuepress/dist
    - run: git init
    - run: git add -A
    - run: git config user.email "av@av.com"
    - run: git config user.name "AV"
    - run: git commit -m 'deploy'
    - run: ssh -T git@github.com
    - run: git push -f git@github.com:ajilalv/avapps-doc.git main:gh-pages
