name: Build and Deploy
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
    - run:
          npm install -D vuepress
    - run:
          npm run docs:build
    - run:
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:ajilalv/avapps-doc.git main:gh-pages
