name: Build and Deploy
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: ajilalv/avapps-doc@main
    - run:
          npm run docs:build
