name: Build and Deploy v2
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ajilalv/avapps-site
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm install -D vuepress && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/
